fix: error when the wrong build is being built

diff --git a/nobodywho/unity/justfile b/nobodywho/unity/justfile
--- a/nobodywho/unity/justfile
+++ b/nobodywho/unity/justfile
@@ -95,9 +95,19 @@ clean-all:
 
 build-plugin:
     #!/usr/bin/env bash
+    rm -f ./src/Runtime/Plugins/x86_64/libnobodywho.so
+    rm -f ../target/debug/libnobodywho_unity.so # ensure that the old plugin is removed.
     cargo build
+    if [ $? -ne 0 ]; then
+        echo "❌ Cargo build failed!"
+        exit 1
+    fi
     mkdir -p ./src/Runtime/Plugins/x86_64
-    cp "../target/debug/libunity_plugin.so" "./src/Runtime/Plugins/x86_64/libnobodywho.so"
+    cp "../target/debug/libnobodywho_unity.so" "./src/Runtime/Plugins/x86_64/libnobodywho.so"
+    if [ $? -ne 0 ]; then
+        echo "❌ Build failed!"
+        exit 1
+    fi
     
     echo "✅ Build complete!"
 
